apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: k8s-app-resources
  namespace: argo-cd
spec:
  description: Project for managing Kubernetes application resources
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
