{{- range .Values.clusters }}
{{- if .apps.enabled }}
{{- if .apps.pythonApi.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{printf "%s-%s" .name "python-api"}}
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: k8s-app-resources
  source:
    repoURL: https://github.com/sarubhai/argo-cd-app-of-apps-pattern.git
    targetRevision: {{ .apps.pythonApi.version }}
    path: 4_app_of_apps_configurable/app-charts/python-api
    helm:
      releaseName: python-api
      valueFiles:
        - {{ .apps.valueFiles }}
      version: v3
  destination:
    name: {{ .name }}
    namespace: python-api
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
{{- end }}
{{- end }}
---
{{- end }}
