apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: k8s-cluster-tools
  sources:
    - repoURL: https://charts.external-secrets.io
      chart: external-secrets
      targetRevision: 0.10.6
      helm:
        valueFiles:
          - $values/1_simple/apps/external-secrets/values.yaml
    - repoURL: https://github.com/sarubhai/argo-cd-app-of-apps-pattern.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    # name: in-cluster
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
