apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps-infra
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: k8s-infra-resources
  source:
    repoURL: https://github.com/sarubhai/argo-cd-app-of-apps-pattern.git
    targetRevision: HEAD
    path: 4_app_of_apps_configurable/app-of-apps-infra
  destination:
    server: https://kubernetes.default.svc
    # name: in-cluster
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
